services:
    mysql:
        image: mysql
        container_name: MYSQL
        restart: always
        ports:
            - "33060:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
        volumes:
            - ./dbata:/var/lib/mysql
